config/routes.rb
Rails.application.routes.draw do
    resources :categories, only: [:index, :show] do
        resources :flavors
    end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :flavors
end

app/models/flavor.rb
class Flavor < ApplicationRecord
    belongs_to :category
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    def index
        @categories = Category.all
    end

    def show
        @category = Category.find(params[:id])
        @flavors = Flavor.where(category_id: params[:id])
    end
end

app/controllers/flavors_controller.rb
class FlavorsController < ApplicationController
    def index
        # @category = Category.find(params[:id])
        # @flavors = Flavor.where(category_id: params[:id]) 
    end

    def show
        @flavor = Flavor.find(params[:id])
    end

    def create
        flavor = params["flavor"]
        @category = Category.find(params[:category_id])
        Flavor.create(name: flavor["name"],
                        base_flavor: flavor["base_flavor"],
                        description: flavor["description"],
                        picture_url: flavor["picture_url"],
                        category_id: @category["id"])
        redirect_to category_path(@category)                  
    end

    def update
        flavor = params["flavor"]
        @category = Category.find(params[:category_id])
        Flavor.update(params[:id],
                        name: flavor["name"],
                        base_flavor: flavor["base_flavor"],
                        description: flavor["description"],
                        picture_url: flavor["picture_url"],
                        category_id: @category["id"])
        redirect_to category_path(@category)
    end

    def destroy
        @category = Category.find(params[:category_id])
        Flavor.destroy(params[:id])
        redirect_to category_path(@category)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flavors_helper.rb
module FlavorsHelper
end

app/views/categories/_footer.html.erb
<div class = 'footer-container'>
<h3 class = 'footer'>Created With Much ❤️ and Especially 🍨 By Jake Meltzer</h3>
</div>

app/views/categories/_header.html.erb
<div class = 'header-container'>
<h1 class = 'header'>Ben & Jerry's Power Rankings!</h1>
<h4 class = 'sub-header'>Rank Your Favorite Flavors in 4 Separate Categories</h4>
</div>

app/views/categories/index.html.erb
<div class = 'categories-container'>
<%= render 'header' %>
<ul class = 'categories'>
<% @categories.each do |category| %>
    <li class = 'category'><%= link_to category.name, category_path(category) %></li>    
<% end %>
</ul>
<%= render 'footer' %>
</div>   

app/views/categories/show.html.erb
<div class = 'flavors-container'>
<%= render 'header' %>
<h1 class = 'flavor-header'><%= @category.name %> Flavors</h1>

<ol class = 'flavors-list'>
    <% @flavors.each do |flavor| %>
        <li class = 'flavor'> <%= link_to flavor.name, category_flavor_path(@category, flavor) %></li>
        <%= image_tag flavor.picture_url, class: 'flavor-image' %> <br>
        <%= link_to "Edit Flavor", edit_category_flavor_path(@category, flavor), :class => 'edit' %>
    <% end %>    
</ol>

<div class = 'links'>
<%= link_to "Add New Flavor", new_category_flavor_path(params[:id], :class => 'add-flavor') %><br>

<%= link_to "Flavor Categories", categories_path, :class => 'categories-back' %>
</div>
<%= render 'footer' %>
</div>

app/views/flavors/_footer.html.erb
<div class = 'footer-container'>
<h3 class = 'footer'>Created With Much ❤️ and Especially 🍨 By Jake Meltzer</h3>
</div>

app/views/flavors/_header.html.erb
<div class = 'header-container'>
<h1 class = 'header'>Ben & Jerry's Power Rankings!</h1>
</div>

app/views/flavors/edit.html.erb
<div class = 'edit-form-container'>
<%= render 'header' %>
<%= form_for :flavor, method: 'patch', url: {action: 'update'}, html: {class: 'form'} do |f| %>
    <%= label(:flavor, :name, class: 'label') %> &nbsp;
    <%= f.text_field :name, class: 'input' %>
    <br>
    <%= label(:flavor, :base_flavor, class: 'label') %> &nbsp;
    <%= f.text_field :base_flavor, class: 'input' %>
    <br>
    <%= label(:flavor, :description, class: 'label') %> &nbsp;
    <%= f.text_field :description, class: 'input' %>
    <br>
    <%= label(:flavor, :picture_url, class: 'label') %> &nbsp;
    <%= f.text_field :picture_url, class: 'input' %>
    <br>
    <%= f.submit class: 'submit' %>
<% end %>

<%= render 'footer' %>
</div>

app/views/flavors/new.html.erb
<div class = 'add-form-container'>
<%= render 'header' %>
<%= form_for :flavor, method: 'post', url: {action: 'create'}, html: {class: 'form'} do |f| %>
    <%= label(:flavor, :name, class: 'label') %> &nbsp;
    <%= f.text_field :name, class: 'input' %>
    <br>
    <%= label(:flavor, :base_flavor, class: 'label') %> &nbsp;
    <%= f.text_field :base_flavor, class: 'input' %>
    <br>
    <%= label(:flavor, :description, class: 'label') %> &nbsp;
    <%= f.text_field :description, class: 'input' %>
    <br>
    <%= label(:flavor, :picture_url, class: 'label') %> &nbsp;
    <%= f.text_field :picture_url, class: 'input' %>
    <br>
    <%= f.submit class: 'submit' %>
<% end %> 

<%= render 'footer' %>
</div>

app/views/flavors/show.html.erb
<div class = 'single-flavor'>
<%= image_tag @flavor.picture_url, class: 'flavor-image' %>

<h1 class = 'flavor-name'><%= @flavor.name %> </h1>
<h3 class = 'base-flavor'>Base Flavor(s): <%= @flavor.base_flavor %></h3>
<p class = 'description'><%= @flavor.description %></h3>
<br>

<div class = 'links'>
<%= link_to "Back to Flavors", category_path(params[:category_id]), :class => 'flavors-back' %><br>
<%= link_to "Delete Flavor", category_flavor_path(params[:category_id], params[:id]), method: 'delete' %>
</div>
<%= render 'footer' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BenAndJerrysPowerRankings</title>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Cherry+Cream+Soda|Chewy" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>